debug: true
auction:
  maxAuctions:
    player: 10
    overall: 20
    opIgnore: true
  undoTime: 20s
  maxLength: 1d
  standardLength: 30m
  opCanCheat: true
  timeFormat: "dd/MM/yy HH:mm"
  blacklist: []

