name: AuctionHouse
version: "${project.version}"
main: de.paralleluniverse.Faithcaio.AuctionHouse.AuctionHouse
#commands:
depend:
  - Vault
softdepend: []
database: false
website: "http://parallel-universe.de"
description: ""
authors:
  - "Faithcaio"
  - "Quick_Wango"
load: postworld
#permissions:
