name: AuctionHouse
version: "${project.version}"
main: de.paralleluniverse.Faithcaio.AuctionHouse.AuctionHouse
commands:
  auctionhouse:
    description: "This is the base command of AuctionHouse"
    usage: "/<command> <action>"
    aliases:
      - ah
depend:
  - Vault
database: false
website: "http://parallel-universe.de"
description: ""
authors:
  - "Faithcaio"
  - "Quick_Wango"
permissions:
  auctionhouse.*:
    description: "Allows the player to do everything"
    default: op
    children:
      auctionhouse.cheatItems: true
      auctionhouse.use.*: true
      auctionhouse.delete.*: true
      auctionhouse.info.*: true
      auctionhouse.getItems.command: true
      auctionhouse.help: true
      auctionhouse.notify.*: true
      auctionhouse.help: true
      auctionhouse.search: true

  auctionhouse.use.*:
    description: ""
    children:
      auctionhouse.use.bid: true
      auctionhouse.use.add: true
      auctionhouse.use.add.multi: true
      auctionhouse.use.undobid: true
    

  auctionhouse.use.bid:
    description: ""
    
  auctionhouse.use.add:
    description: ""
    
  auctionhouse.use.add.multi:
    description: ""
    
  auctionhouse.use.undobid:
    description: ""

  auctionhouse.delete.*:
    description: ""
    children:
      auctionhouse.delete.all: true
      auctionhouse.delete.player: true
      auctionhouse.delete.player.other: true
      auctionhouse.delete.id: true
    

  auctionhouse.delete.all:
    description: ""
    
  auctionhouse.delete.player:
    description: ""
    
  auctionhouse.delete.id:
    description: ""
    
  auctionhouse.delete.player.other:
    description: ""

  auctionhouse.cheatItems:
    description: ""

  auctionhouse.info.*:
    description: ""
    children:
      auctionhouse.info: true
      auctionhouse.info.others: true

  auctionhouse.info:
    description: ""
    
  auctionhouse.info.others:
    description: ""

  auctionhouse.notify.*:
    description: ""
    children:
      auctionhouse.notify.command: true
      auctionhouse.notify: true

  auctionhouse.notify.command:
    description: ""
    
  auctionhouse.notify:
    description: ""

  auctionhouse.help:
    description: ""
    
  auctionhouse.search:
    description: ""
    
  auctionhouse.getItems.command:
    description: ""