name: AuctionHouse
version: "${project.version}"
main: de.paralleluniverse.Faithcaio.AuctionHouse.AuctionHouse
commands:
  auctionhouse:
    description: "This is the base command of AuctionHouse"
    usage: "/<command> <action>"
    aliases:
      - ah
depend:
  - Vault
database: false
website: "http://parallel-universe.de"
description: ""
authors:
  - "Faithcaio"
  - "Quick_Wango"
permissions:
  auctionhouse.*:
    description: "Allows the player to do everything"
    default: op
    children:
      auctionhouse.cheatItems: true
      auctionhouse.use.*: true
      auctionhouse.delete.*: true
      auctionhouse.info.*: true
      auctionhouse.getItems.command: true
      auctionhouse.help: true
      auctionhouse.notify.*: true
      auctionhouse.help: true
      auctionhouse.search: true
      
  auctionhouse.use.*:
    children:
      auctionhouse.use.bid: true
      auctionhouse.use.add: true
      auctionhouse.use.add.multi: true
      auctionhouse.use.undobid: true
      
  auctionhouse.use.bid:    
  auctionhouse.use.add:
  auctionhouse.use.add.multi:
  auctionhouse.use.undobid:
  
  auctionhouse.delete.*:
    children:
      auctionhouse.delete.all: true
      auctionhouse.delete.player: true
      auctionhouse.delete.player.other: true
      auctionhouse.delete.id: true
    
  auctionhouse.delete.all:
  auctionhouse.delete.player:
  auctionhouse.delete.id:
  auctionhouse.delete.player.other: 
    
  auctionhouse.cheatItems:
  
  auctionhouse.info.*:
    children:
      auctionhouse.info: true
      auctionhouse.info.others: true

  auctionhouse.info:
  auctionhouse.info.others:

  auctionhouse.notify.*:
    children:
      auctionhouse.notify.command: true
      auctionhouse.notify: true
  
  auctionhouse.notify.command:
  auctionhouse.notify:
    
  auctionhouse.help:
  auctionhouse.search:
  auctionhouse.getItems.command:  