name: AuctionHouse
version: "${project.version}"
main: de.paralleluniverse.Faithcaio.AuctionHouse.AuctionHouse
commands:
  auctionhouse:
    description: "This is the base command of AuctionHouse"
    usage: "/<command> <action>"
    aliases:
      - ah
depend:
  - Vault
database: false
website: "http://parallel-universe.de"
description: ""
authors:
  - "Faithcaio"
  - "Quick_Wango"
#permissions:
