name: AuctionHouse
version: "${project.version}"
main: de.cubeisland.AuctionHouse.AuctionHouse
commands:
  auctionhouse:
    description: "This is the base command of AuctionHouse"
    usage: "/<command> <action>"
    aliases:
      - ah
depend:
  - Vault
database: false
website: "http://parallel-universe.de"
description: ""
authors:
  - "Faithcaio"
  - "Quick_Wango"

permissions:
  auctionhouse.admin:
    description: "Can do everything"
    children: 
      auctionhouse.*: true
      
  auctionhouse.mod:
    description: "All normal Commands"
    children: 
      auctionhouse.user.command: true
      auctionhouse.delete.server: true
      auctionhouse.delete.player.other: true
      auctionhouse.create.*: true
      
  auctionhouse.user.command:
    description: "All normal Commands"
    children: 
      auctionhouse.user: true
      auctionhouse.use.*: true
      auctionhouse.getItems.command: true
      
  auctionhouse.user:
    description: "Can not Start Auction or receive items with command"
    children:
      auctionhouse.use.bid: true
      auctionhouse.use.undobid: true
      auctionhouse.use.addsign: true
      auctionhouse.delete.id: true
      auctionhouse.delete.player: true
      auctionhouse.info.*: true
      auctionhouse.getItems.sign: true
      auctionhouse.help: true
      auctionhouse.search: true
      auctionhouse.notify.*: true

  auctionhouse.*:
    description: "Allows the player to do everything"
    default: op
    children:
      auctionhouse.cheatItems: true
      auctionhouse.use.*: true
      auctionhouse.delete.all: true
      auctionhouse.info.*: true
      auctionhouse.getItems.*: true
      auctionhouse.help: true
      auctionhouse.notify.*: true
      auctionhouse.search: true
      auctionhouse.use.bid.infinite: true
      auctionhouse.create.*: true

  auctionhouse.use.*:
    description: ""
    children:
      auctionhouse.use.bid: true
      auctionhouse.use.add: true
      auctionhouse.use.add.multi: true
      auctionhouse.use.undobid: true
      auctionhouse.use.addsign: true

  auctionhouse.use.bid:
    description: ""
    
  auctionhouse.use.bid.infinite:
    description: ""
    
  auctionhouse.use.add:
    description: ""
    
  auctionhouse.use.add.multi:
    description: ""
    
  auctionhouse.use.undobid:
    description: ""
    
  auctionhouse.use.addsign:
    description: ""

  auctionhouse.delete.all:
    description: ""
    children:
      auctionhouse.delete.player: true
      auctionhouse.delete.player.other: true
      auctionhouse.delete.id: true
      auctionhouse.delete.server: true

  auctionhouse.delete.player:
    description: ""
    
  auctionhouse.delete.id:
    description: ""
    
  auctionhouse.delete.player.other:
    description: ""

  auctionhouse.delete.server:
    description: ""

  auctionhouse.cheatItems:
    description: ""

  auctionhouse.info.*:
    description: ""
    children:
      auctionhouse.info: true
      auctionhouse.info.others: true

  auctionhouse.info:
    description: ""
    
  auctionhouse.info.others:
    description: ""

  auctionhouse.notify.*:
    description: ""
    children:
      auctionhouse.notify.command: true
      auctionhouse.notify: true

  auctionhouse.notify.command:
    description: ""
    
  auctionhouse.notify:
    description: ""

  auctionhouse.help:
    description: ""
    
  auctionhouse.search:
    description: ""
    
  auctionhouse.getItems.*:
    description: ""
    children:
      auctionhouse.getItems.command: true
      auctionhouse.getItems.sign: true
  
  auctionhouse.getItems.command:
    description: ""
  
  auctionhouse.getItems.sign:
    description: ""
  
  auctionhouse.create.*:
    description: ""  
    children:
      auctionhouse.create.boxsign: true
      auctionhouse.create.addsign: true
    
  auctionhouse.create.boxsign:
    description: ""
    
  auctionhouse.create.addsign:
    description: ""

    
    
